version: '2.2'
services:
  auth-db:
    container_name: auth-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - auth-db:/var/lib/postgresql/data
  locs-db:
    container_name: locs-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - locs-db:/var/lib/postgresql/data
  auth-api:
    build:
      context: ./
      dockerfile: ./auth.Dockerfile
    container_name: auth-api
    image: escritura-auth
    depends_on: [locs-db]
    ports:
      - '8080:8080'
    environment:
      ENV : envvar
  locs-api:
    build:
      context: ./
      dockerfile: ./locs.Dockerfile
    container_name: locs-api
    image: escritura-locs
    depends_on: [auth-api]
    ports:
      - '8081:8081'
    environment:
      ENV : envvar
  email-api:
    build:
      context: ./
      dockerfile: ./email.Dockerfile
    container_name: email-api
    image: escritura-email
    depends_on: [auth-api]
    environment:
      ENV : envvar
volumes:
  auth-db:
    driver: local
  locs-db:
    driver: local
