version: '2.2'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      ENV: 'ENV'
    ports:
      - "5672:5672"
      - "15672:15672"
  auth-db:
    container_name: auth-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      ENV: 'ENV'
    ports:
      - '5432:5432'
    volumes:
      - auth-db:/var/lib/postgresql/data
  locs-db:
    container_name: locs-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      ENV: 'ENV'
    ports:
      - '5432:5432'
    volumes:
      - locs-db:/var/lib/postgresql/data
  auth-api:
    build:
      context: ./
      dockerfile: ./staging.auth.Dockerfile
    container_name: auth-api
    depends_on: [auth-db, rabbitmq]
    ports:
      - "5672:5672"
      - '8080:8080'
    environment:
      ENV: 'ENV'

  locs-api:
    build:
      context: ./
      dockerfile: ./staging.locs.Dockerfile
    container_name: locs-api
    depends_on: [auth-api]
    ports:
      - '8081:8081'
    environment:
      ENV: 'ENV'
  email-api:
    build:
      context: ./
      dockerfile: ./staging.email.Dockerfile
    container_name: email-api
    depends_on: [rabbitmq]
    environment:
      ENV: 'ENV'
    ports:
      - "543:543"
      - "5672:5672"

secrets:
  RABBITMQ_DEFAULT_USER:
    file: .env
  RABBITMQ_DEFAULT_PASS:
    file: .env

  AUTH_PG_HOST:
    file: .env
  AUTH_PG_PORT:
    file: .env
  AUTH_PG_DATABASE:
    file: .env
  AUTH_PG_USER:
    file: .env
  AUTH_PG_PW:
    file: .env


  LOCS_PG_HOST:
    file: .env
  LOCS_PG_PORT:
    file: .env
  LOCS_PG_DATABASE:
    file: .env
  LOCS_PG_USER:
    file: .env
  LOCS_PG_PW:
    file: .env

  AUTH_SPRING_USERNAME:
    file: .env
  AUTH_SPRING_PASSWORD:
    file: .env
  AUTH_PLATFORM_CODE:
    file: .env
  AUTH_LINK_CODE:
    file: .env
  AUTH_PW_CODE:
    file: .env
  AUTH_DATABASE_DRIVER:
    file: .env
  AUTH_DATABASE_PLATFORM:
    file: .env
  AUTH_MQ_QUEUE:
    file: .env
  AUTH_MQ_TOPIC:
    file: .env
  AUTH_MQ_VIRTUAL_HOST:
    file: .env
  AUTH_MQ_HOST:
    file: .env
  AUTH_MQ_USERNAME:
    file: .env
  AUTH_MQ_PASSWORD:
    file: .env

  LOCS_SPRING_USERNAME:
    file: .env
  LOCS_SPRING_PASSWORD:
    file: .env
  LOCS_PLATFORM_CODE:
    file: .env
  LOCS_LINK_CODE:
    file: .env
  LOCS_PW_CODE:
    file: .env
  LOCS_DATABASE_DRIVER:
    file: .env
  LOCS_DATABASE_PLATFORM:
    file: .env

  MQ_QUEUE:
    file: .env
  MQ_TOPIC:
    file: .env
  MQ_VIRTUAL_HOST:
    file: .env
  MQ_HOST:
    file: .env
  MQ_USERNAME:
    file: .env
  MQ_PASSWORD:
    file: .env

  EMAIL_HOST:
    file: .env
  EMAIL_PW:
    file: .env
  EMAIL_PORT:
    file: .env
  EMAIL_EMAIL:
    file: .env

