version: '2.2'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  auth-db:
    container_name: auth-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - auth-db:/var/lib/postgresql/data
  locs-db:
    container_name: locs-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - locs-db:/var/lib/postgresql/data
  auth-api:
    build:
      context: ./
      dockerfile: ./dev.auth.Dockerfile
    container_name: auth-api
    depends_on: [auth-db]
    ports:
      - '8080:8080'
    environment:
      profile : dev
  locs-api:
    build:
      context: ./
      dockerfile: ./dev.locs.Dockerfile
    container_name: locs-api
    depends_on: [auth-api]
    ports:
      - '8081:8081'
    environment:
      ENV : envvar
  email-api:
    build:
      context: ./
      dockerfile: ./dev.email.Dockerfile
    container_name: email-api
    depends_on: [rabbitmq, auth-api]
    environment:
      ENV : envvar
volumes:
  auth-db:
    driver: local
  locs-db:
    driver: local
